development:
  sessions:
    default:
      database: todo_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: todo_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: todo
      hosts:
        - localhost:27017